### ISSUE TITLE
Support for n-grams

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/term-vector#1]
Possibility to return vectors of n-grams, and not just 1-grams

**Comment by mewwts** [comment]
I think this is fixed right?

**Comment by fergiemcdowall** [comment]
Tis indeed

**Comment by fergiemcdowall** [comment]
Oh no- its just fixed in term-vector, not search-index

**Comment by mewwts** [comment]
Should we move it to search-index then?

**Comment by fergiemcdowall** [comment]
Yes we should :)
